### ISSUE TITLE
Issue with online store doc `db_schema: feature_store` leading to no data ingested to online store

### ISSUE THREAD

**Issue by yingding** [nossrannug/feast-postgres#6]
I followed your doc for the online store at https://pypi.org/project/feast-postgres/
```
project: feature_repo
registry: data/registry.db
provider: local
online_store:
    type: feast_postgres.PostgreSQLOnlineStore # MUST be this value
    ...
    db_schema: feature_store   # Optional, default is None
    ...
    password: password
offline_store:
    ...
```
As I did as you suggested, no data is ingested into my postgres (14.1) remote online store, and also no error occurs. 

After I remove the `db_schema: feature_store` to use default None. The data are ingested into the remote postgres db.
In your doc as the following indicating the `db_schema` is just a name for the postgres schema and i can put everything there.
```
if db_schema is set then that value will be used when creating the schema, else the name of the schema will be the value in user
```

Is there maybe a bug for the db_schema name in feast-postgres or in feast?

** update **
```
feast: 0.15.1
feast-postgres: 0.20.0
python: 3.8.10
```

**Comment by nossrannug** [comment]
Hey @yingding , thank you for reporting the issue.
Just so that I understand this 100%. You created the feature_store.yaml, and some_file.py. You then ran `feast apply` and then `feast materialize`?
- Was there no error running feast apply?
- was there no error running feast materialize? Did you see any progress?
- Are you able to reproduce the issue?

**Comment by nossrannug** [comment]
I'm able to run feast materialize without running feast apply. This doesn't give an error, but also doesn't materialize anything since there is no registry with information on what to materialize. Is there any chance that you might have missed running feast apply before running feast materialize?

**Comment by yingding** [comment]
> Hey @yingding , thank you for reporting the issue. Just so that I understand this 100%. You created the feature_store.yaml, and some_file.py. You then ran `feast apply` and then `feast materialize`?

@nossrannug Thanks also for the great work and your rapid response, I did `feast init` first and then edited `feature_store.yaml` and called `feast apply`, and lastly `feast materialize-incremental`. I made a notebook for my approach, maybe it can be a help https://github.com/careforrare/kf-pipelines/blob/feature/fsfeast/featurestore-examples/feast_feature_store.ipynb

> * Was there no error running feast apply?
No
> * was there no error running feast materialize? Did you see any progress?
I called `feast materialize-incremental ...` and got the following output
```
Materializing 2 feature views to 2021-11-23 14:02:11+00:00 into the feast_postgres.PostgreSQLOnlineStore online store.

driver_hourly_stats from 2021-11-23 09:59:07+00:00 to 2021-11-23 14:02:11+00:00:
0it [00:00, ?it/s]
proteome_olink_observations from 2021-11-23 09:59:07+00:00 to 2021-11-23 14:02:11+00:00:
0it [00:00, ?it/s]
```
> * Are you able to reproduce the issue?
Yes, I now did it a couple of times, with `db_schema: feature_store` and `feast apply` then `feast materialize-incremental $(date -u +"%Y-%m-%dT%H:%M:%S")`, i only see a empty `public` schema in my postgres 14.1.
I commented out the `# db_schema: feature_store` to use default none, saved feature_store.yaml and `feast apply` then `feast materialize-incremental $(date -u +"%Y-%m-%dT%H:%M:%S")`, then i can immediately see a schema of my postgres user is created and the `feature_repo_driver_hourly_stats` are there. I then drop the table and schema and redone the same approach again. It appears to me with `db_schema:feature_store` no data is ingested and i don't get any error.

Could it be the case, postgres don't like `feature_store` as schema name?

**Comment by yingding** [comment]
> I'm able to run feast materialize without running feast apply. This doesn't give an error, but also doesn't materialize anything since there is no registry with information on what to materialize. Is there any chance that you might have missed running feast apply before running feast materialize?

Since it is a jupyter notebook, thus I really see that I applyed first and also see the output
```
Registered entity driver_id
Registered feature view driver_hourly_stats
Deploying infrastructure for driver_hourly_stats
```
I am not sure if you can reproduce on your end.

**Comment by nossrannug** [comment]
The schema and tables are created when you run feast apply. If for some reason the user is unable to create the schema or tables then an error is thrown and it should get all the way to the user since there is nothing catching it.

I have been using this config:
```
online_store:
  type: feast_postgres.PostgreSQLOnlineStore
  host: my.cloud.com
  port: 5432
  database: feature_db
  db_schema: feature_store
  user: my_user
  password: my_password
```

When I run feast apply, the schema is created and all the tables. If I comment out the db_schema and run feast apply then I get a schema with the same name as the user.
Could it be some setting that´s hiding the feature_store schema from you?

---

I've noticed that unless there is some data to materialize, there is no error even if the schema and table are missing.
Can you try running this command when you materialize the features:
```
feast materialize "2010-10-10T00:00:00" $(date -u +"%Y-%m-%dT%H:%M:%S")
```
Just to make sure that some features get materialize. I think that materialize incremental will only look back to the timestamp when you created the feature store.

**Comment by yingding** [comment]
> Could it be some setting that´s hiding the feature_store schema from you?
Really sorry for this, you are right. I double checked my visual tool for postgres, which only shows the default schema. That war my issue. Please feel free to close this issue.
